management:
  endpoints:
    web:
      buildpath: /
      exposure:
        include: hystrix.stream

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        requestVolumeThreshold: 5
        sleepWindowInMilliseconds: 10000


feign:
  hystrix:
    enabled: true
